-- =====================================================
-- STEP 4: Staging Layer – Data Cleaning & Standardization
-- Cleans nulls, formats date, recalculates profit
-- =====================================================

create or replace schema staging_layer;

CREATE OR REPLACE TABLE STG_RETAIL AS
SELECT
    TRANSACTION_ID,
    COALESCE(
        TRY_TO_DATE(TRANSACTION_DATE, 'YYYY/MM/DD'),
        TRY_TO_DATE(TRANSACTION_DATE, 'DD-MM-YYYY'),
        TRY_TO_DATE(TRANSACTION_DATE, 'YYYY-MM-DD')
    ) AS TRANSACTION_DATE,
    COALESCE(REGION, 'UNKNOWN') AS REGION,
    PRODUCT,
    TRY_TO_NUMBER(CUSTOMER_ID) AS CUSTOMER_ID,
    TRY_TO_NUMBER(SALES_AMOUNT) AS SALES_AMOUNT,
    TRY_TO_NUMBER(COST_AMOUNT) AS COST_AMOUNT,
    TRY_TO_NUMBER(PROFIT_REPORTED) AS PROFIT_REPORTED,
    TRY_TO_NUMBER(SALES_AMOUNT) - TRY_TO_NUMBER(COST_AMOUNT) AS CALCULATED_PROFIT,

    CASE 
        WHEN TRY_TO_NUMBER(PROFIT_REPORTED) =
             TRY_TO_NUMBER(SALES_AMOUNT) - TRY_TO_NUMBER(COST_AMOUNT)
        THEN 'VALID'
        ELSE 'MISMATCH'
    END AS PROFIT_VALIDATION_FLAG,

    TRY_TO_NUMBER(DISCOUNT_PERCENTAGE) AS DISCOUNT_PERCENTAGE,

    COALESCE(PAYMENT_METHOD, 'UNKNOWN') AS PAYMENT_METHOD,

    /* Duplicate Detection */
    COUNT(*) OVER (PARTITION BY TRANSACTION_ID) AS DUPLICATE_COUNT

FROM RAW_LAYER.RETAIL_RAW;

-- Validate cleaned row count
SELECT COUNT(*) FROM stg_retail;
